process.on("uncaughtException",function(a){console.log("blah");throw a});throw"on purpose";